## Please follow the below structure while attempting the hackathon, make sure to submit only one jupyter file with all the models, and you can always mention your best model by giving it the header as 'Best Model'.

## Please make sure to maintain the clarity of analysis in the notebook with proper headers and inisghts/inferences, so that it can be interpretable 


## Please follow the same format as mentioned below, as you will be evaluated basis on your Jupyter Notebook for L2 selection.

## Importing Necessary Libraries

In [61]:
import numpy as np
import pandas as pd

In [69]:
train_df=pd.read_csv("Data_Train.csv")
test_df=pd.read_csv("Data_Test.csv")

In [70]:
train_df.head()

ID  Asst_Reg GGGrade Experience       Validation  Yearly Income  \
0   95074    421802      II     >10yrs            Vfied      633600.00   
1  134131   3964312      IV       7yrs  Source Verified       85483.20   
2   92602   4247560     III       <1yr  Source Verified       79200.00   
3   22591    197179     III       <1yr            Vfied       61600.00   
4  125060   4646684       V       2yrs  Source Verified       68053.92   

  Home Status  Unpaid 2 years  Already Defaulted       Designation  ...  \
0    MOR??AGE               0                  0   GLENDALE NISSAN  ...   
1        REN?               0                  0  Business Teacher  ...   
2        REN?               0                  0            driver  ...   
3        REN?               0                  0          AvePoint  ...   
4        REN?               0                  0       Lead Tester  ...   

   File Status       State  Account Open  Total Unpaid CL  Duration  \
0   fully paid  California            17          58598.0   3 years   
1        whole          NC            15          18924.0   5 years   
2        whole     Florida             7          15604.0   5 years   
3   fully paid   NewJersey             9          22410.0   3 years   
4   fully paid          LA            10          36022.0   5 years   

   Unpaid Amount               Reason  Claim Type  Due Fee  Loan/No Loan  
0       31216.05  debt  consolidation           I      0.0             0  
1       11660.49  debt  consolidation           I      0.0             0  
2        5637.87      major  purchase           I      0.0             0  
3       15607.17      major  purchase           I      0.0             1  
4       27472.86  debt  consolidation           I      0.0             0  

[5 rows x 30 columns]

In [71]:
train_df.tail()

ID  Asst_Reg GGGrade Experience       Validation  Yearly Income  \
87495  120884   4535984      II     >10yrs        Not Vfied       75680.00   
87496   33259   2624710      IV       3yrs  Source Verified       90423.52   
87497  102153   5966919      II     >10yrs  Source Verified       91520.00   
87498  115343   2630667     III       1yrs  Source Verified       61600.00   
87499  104968   6637289     III       2yrs            Vfied            NaN   

      Home Status  Unpaid 2 years  Already Defaulted            Designation  \
87495        REN?               0                  0    Engineer Support II   
87496        REN?               0                  0       Dental Hygienist   
87497    MOR??AGE               0                  0  Interface Coordinator   
87498    MOR??AGE               0                  0            PARTS CLERK   
87499        REN?               0                  0      Outside sales rep   

       ...  File Status       State  Account Open  Total Unpaid CL  Duration  \
87495  ...        whole          MI            12          32702.0   3 years   
87496  ...        whole          MA            23          32204.0   5 years   
87497  ...   fully paid          CT             8          29050.0   3 years   
87498  ...        whole          PA            11          24900.0   3 years   
87499  ...        whole  California             7          21746.0   5 years   

       Unpaid Amount               Reason  Claim Type  Due Fee  Loan/No Loan  
87495       10012.05  debt  consolidation           I      0.0             0  
87496       24921.54  debt  consolidation           I      0.0             0  
87497       14517.90  debt  consolidation           I      0.0             0  
87498        8454.24  debt  consolidation           I      0.0             0  
87499        8717.58  debt  consolidation           I      0.0             0  

[5 rows x 30 columns]

In [72]:
print("Rows: "+str(train_df.shape[0])+" & "+"Columns: "+str(train_df.shape[1]))


Rows: 87500 & Columns: 30


In [73]:
train_df.describe(include="all").T

count unique                  top   freq  \
ID                   87500.0    NaN                  NaN    NaN   
Asst_Reg             87500.0    NaN                  NaN    NaN   
GGGrade                87500      7                   II  24966   
Experience             87500     11               >10yrs  30849   
Validation             87500      3      Source Verified  34504   
Yearly Income        81925.0    NaN                  NaN    NaN   
Home Status            87500      5             MOR??AGE  44160   
Unpaid 2 years       87500.0    NaN                  NaN    NaN   
Already Defaulted    87500.0    NaN                  NaN    NaN   
Designation            86086  40354       School Teacher   1585   
Debt to Income       84011.0    NaN                  NaN    NaN   
Postal Code          86111.0    NaN                  NaN    NaN   
Lend Amount          87500.0    NaN                  NaN    NaN   
Deprecatory Records  87500.0    NaN                  NaN    NaN   
Interest Charged     87500.0    NaN                  NaN    NaN   
Usage Rate           87500.0    NaN                  NaN    NaN   
Inquiries            87500.0    NaN                  NaN    NaN   
Present Balance      87500.0    NaN                  NaN    NaN   
Gross Collection     87500.0    NaN                  NaN    NaN   
Sub GGGrade          87500.0    NaN                  NaN    NaN   
File Status            87500      2                whole  46300   
State                  87500     49           California  12625   
Account Open         87500.0    NaN                  NaN    NaN   
Total Unpaid CL      83314.0    NaN                  NaN    NaN   
Duration               87500      2              3 years  60061   
Unpaid Amount        82648.0    NaN                  NaN    NaN   
Reason                 87500     13  debt  consolidation  52559   
Claim Type             87500      2                    I  87454   
Due Fee              87500.0    NaN                  NaN    NaN   
Loan/No Loan         87500.0    NaN                  NaN    NaN   

                               mean             std      min         25%  \
ID                     83946.253509     36100.10295  21560.0    52616.75   
Asst_Reg             3798914.124149  2289038.082588  24847.0  1483874.25   
GGGrade                         NaN             NaN      NaN         NaN   
Experience                      NaN             NaN      NaN         NaN   
Validation                      NaN             NaN      NaN         NaN   
Yearly Income          134859.62978    98824.725562   8800.0   83246.592   
Home Status                     NaN             NaN      NaN         NaN   
Unpaid 2 years             0.332937         0.87608      0.0         0.0   
Already Defaulted          0.005726        0.083505      0.0         0.0   
Designation                     NaN             NaN      NaN         NaN   
Debt to Income             30.94266       14.079813      0.0     20.4288   
Postal Code            51155.385491     31211.22993   1000.0     22900.0   
Lend Amount             25920.53568    14433.837213   1710.0     15048.0   
Deprecatory Records          0.2024        0.646414      0.0         0.0   
Interest Charged          16.518375        4.902011      8.0       12.31   
Usage Rate                95.517348       40.554035      0.0      66.048   
Inquiries                   0.67064        0.959572      0.0         0.0   
Present Balance       236389.464783   255056.781907      0.0    51734.93   
Gross Collection          39.461697      391.919578      0.0         0.0   
Sub GGGrade               22.024891        6.452697     11.0        17.0   
File Status                     NaN             NaN      NaN         NaN   
State                           NaN             NaN      NaN         NaN   
Account Open               12.77944         5.37116      2.0         9.0   
Total Unpaid CL        53268.640394    53255.513914    332.0     23240.0   
Duration                        NaN          

In [74]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87500 entries, 0 to 87499
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   ID                   87500 non-null  int64  
 1   Asst_Reg             87500 non-null  int64  
 2   GGGrade              87500 non-null  object 
 3   Experience           87500 non-null  object 
 4   Validation           87500 non-null  object 
 5   Yearly Income        81925 non-null  float64
 6   Home Status          87500 non-null  object 
 7   Unpaid 2 years       87500 non-null  int64  
 8   Already Defaulted    87500 non-null  int64  
 9   Designation          86086 non-null  object 
 10  Debt to Income       84011 non-null  float64
 11  Postal Code          86111 non-null  float64
 12  Lend Amount          87500 non-null  float64
 13  Deprecatory Records  87500 non-null  int64  
 14  Interest Charged     87500 non-null  float64
 15  Usage Rate           87500 non-null 

In [76]:
train_df.isnull().sum()

ID                        0
Asst_Reg                  0
GGGrade                   0
Experience                0
Validation                0
Yearly Income          5575
Home Status               0
Unpaid 2 years            0
Already Defaulted         0
Designation            1414
Debt to Income         3489
Postal Code            1389
Lend Amount               0
Deprecatory Records       0
Interest Charged          0
Usage Rate                0
Inquiries                 0
Present Balance           0
Gross Collection          0
Sub GGGrade               0
File Status               0
State                     0
Account Open              0
Total Unpaid CL        4186
Duration                  0
Unpaid Amount          4852
Reason                    0
Claim Type                0
Due Fee                   0
Loan/No Loan              0
dtype: int64

In [80]:
train_df.dropna(inplace=True)
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 68505 entries, 0 to 87498
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   ID                   68505 non-null  int64  
 1   Asst_Reg             68505 non-null  int64  
 2   GGGrade              68505 non-null  object 
 3   Experience           68505 non-null  object 
 4   Validation           68505 non-null  object 
 5   Yearly Income        68505 non-null  float64
 6   Home Status          68505 non-null  object 
 7   Unpaid 2 years       68505 non-null  int64  
 8   Already Defaulted    68505 non-null  int64  
 9   Designation          68505 non-null  object 
 10  Debt to Income       68505 non-null  float64
 11  Postal Code          68505 non-null  float64
 12  Lend Amount          68505 non-null  float64
 13  Deprecatory Records  68505 non-null  int64  
 14  Interest Charged     68505 non-null  float64
 15  Usage Rate           68505 non-null 

In [79]:
train_df.corr()

ID  Asst_Reg  Yearly Income  Unpaid 2 years  \
ID                   1.000000 -0.004232      -0.002954       -0.000838   
Asst_Reg            -0.004232  1.000000       0.036625        0.036358   
Yearly Income       -0.002954  0.036625       1.000000        0.051989   
Unpaid 2 years      -0.000838  0.036358       0.051989        1.000000   
Already Defaulted    0.006410  0.008668       0.015004        0.139745   
Debt to Income      -0.001687  0.088797      -0.227349       -0.016802   
Postal Code         -0.002539 -0.015534      -0.005954       -0.030803   
Lend Amount         -0.001500  0.037526       0.410832       -0.015491   
Deprecatory Records -0.000352  0.063968      -0.007496       -0.013334   
Interest Charged     0.000441 -0.003003       0.001859        0.000244   
Usage Rate           0.000641 -0.074336       0.047828       -0.016389   
Inquiries           -0.001699 -0.110090       0.047967        0.032887   
Present Balance      0.005322  0.010424       0.509145        0.062563   
Gross Collection    -0.000138 -0.108796       0.013993        0.001272   
Sub GGGrade         -0.005820 -0.025286      -0.092394        0.059506   
Account Open         0.000952  0.055692       0.158822        0.046248   
Total Unpaid CL      0.003739  0.061365       0.366515       -0.049409   
Unpaid Amount        0.004036  0.033218       0.373161       -0.036141   
Due Fee             -0.002621 -0.066383       0.011635        0.023499   
Loan/No Loan         0.001636 -0.415039      -0.001667       -0.028419   

                     Already Defaulted  Debt to Income  Postal Code  \
ID                            0.006410       -0.001687    -0.002539   
Asst_Reg                      0.008668        0.088797    -0.015534   
Yearly Income                 0.015004       -0.227349    -0.005954   
Unpaid 2 years                0.139745       -0.016802    -0.030803   
Already Defaulted             1.000000        0.002987    -0.006580   
Debt to Income                0.002987        1.000000     0.006881   
Postal Code                  -0.006580        0.006881     1.000000   
Lend Amount                  -0.001469        0.030387    -0.007362   
Deprecatory Records           0.001924       -0.061234    -0.008640   
Interest Charged             -0.000999       -0.002150    -0.001504   
Usage Rate                   -0.029705        0.159477     0.011908   
Inquiries                    -0.006015       -0.003270     0.006919   
Present Balance               0.018236       -0.009675    -0.010834   
Gross Collection              0.001084        0.005480     0.009456   
Sub GGGrade                   0.030263        0.174689    -0.010189   
Account Open                  0.015758        0.289489    -0.049042   
Total Unpaid CL               0.009204        0.083962    -0.035586   
Unpaid Amount                -0.001298        0.136171    -0.028489   
Due Fee                       0.011941       -0.001771    -0.002879   
Loan/No Loan                 -0.007118       -0.088414     0.034917   

                     Lend Amount  Deprecatory Records  Interest Charged  \
ID                     -0.001500            -0.000352          0.000441   
Asst_Reg                0.037526             0.063968         -0.003003   
Yearly Income           0.410832            -0.007496          0.001859   
Unpaid 2 years         -0.015491            -0.013334          0.000244   
Already Defaulted      -0.001469             0.001924         -0.000999   
Debt to Income          0.030387            -0.061234         -0.002150   
Postal Code            -0.007362            -0.008640         -0.001504   
Lend Amount             1.000000            -0.090159         -0.002594   
Deprecatory Records    -0.090159             1.000000          0.004287   
Interest Charged       -0.002594             0.004287          1.000000   
Usage Rate              0.114702            -0.091972         -0.001193   
Inquiries              -0.027013             0.077999         -0.003099   
Prese

In [82]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')
enc.fit(train_df)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='ignore', sparse=True)

In [83]:
enc.categories_

[array([ 21560,  21562,  21563, ..., 146556, 146558, 146559], dtype=int64),
 array([  24847,   30038,   37601, ..., 7351813, 7351831, 7351847],
       dtype=int64),
 array(['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], dtype=object),
 array(['1yrs', '2yrs', '3yrs', '4yrs', '5yrs', '6yrs', '7yrs', '8yrs',
        '9yrs', '<1yr', '>10yrs'], dtype=object),
 array(['Not Vfied', 'Source Verified', 'Vfied'], dtype=object),
 array([   8800.  ,   14615.04,   14784.  , ..., 2640000.  , 4400000.  ,
        5280000.  ]),
 array(['MOR??AGE', 'NONE', 'OTHER', 'OWN', 'REN?'], dtype=object),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        18], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6], dtype=int64),
 array(['(CDL) Bus Driver', '(LAUSD) Lynwood high', '0-3', ..., 'zms',
        'zone manager', 'zookeeper'], dtype=object),
 array([0.000000e+00, 1.344000e-01, 1.512000e-01, ..., 7.613760e+01,
        1.206576e+02, 6.392904e+02]),
 array([ 1000.,  1100.,  1200.,  1300.,  

In [29]:
#As we dont know the yearly income of an individual we can't trust them with disbursing the loan. SO all the null values field of the rows are to be removed
train_df = train_df[train_df['Yearly Income'].notna()]

In [31]:
train_df.isnull().sum()


ID                        0
Asst_Reg                  0
GGGrade                   0
Experience                0
Validation                0
Yearly Income             0
Home Status               0
Unpaid 2 years            0
Already Defaulted         0
Designation            1342
Debt to Income         3257
Postal Code            1296
Lend Amount               0
Deprecatory Records       0
Interest Charged          0
Usage Rate                0
Inquiries                 0
Present Balance           0
Gross Collection          0
Sub GGGrade               0
File Status               0
State                     0
Account Open              0
Total Unpaid CL        3919
Duration                  0
Unpaid Amount          4549
Reason                    0
Claim Type                0
Due Fee                   0
Loan/No Loan              0
dtype: int64

In [33]:
train_df[["Designation",'Yearly Income']]

Designation  Yearly Income
0                     GLENDALE NISSAN      633600.00
1                    Business Teacher       85483.20
2                              driver       79200.00
3                            AvePoint       61600.00
4                         Lead Tester       68053.92
...                               ...            ...
87494  Technical Architecture Manager      246400.00
87495             Engineer Support II       75680.00
87496                Dental Hygienist       90423.52
87497           Interface Coordinator       91520.00
87498                     PARTS CLERK       61600.00

[81925 rows x 2 columns]

In [35]:
train_df['Yearly Income'].max()

8264030.72

In [36]:
train_df['Yearly Income'].min()

8800.0

In [37]:
df=train_df[train_df['Designation'].isna()]['Yearly Income']
df

38        70400.00
51        88000.00
74       112640.00
259       38329.28
357      220000.00
           ...    
87303    133760.00
87305    149600.00
87310    198880.00
87337     70400.00
87490    112640.00
Name: Yearly Income, Length: 1342, dtype: float64

In [51]:
len(train_df['Designation'].value_counts())

38164

In [60]:
AvgSalDesignations={}
j=0
for i in train_df['Designation'].value_counts().iteritems():
    AvgSalDesignations[i[0]]=train_df[train_df['Designation']==i[0]]['Yearly Income'].mean()
    print(j)
    j=j+1
    
    
    
    



0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926


KeyboardInterrupt: 

In [59]:
AvgSalDesignations

{}

In [54]:
train_df['Home Status'].value_counts()

MOR??AGE    41381
REN?        32672
OWN          7862
OTHER           6
NONE            4
Name: Home Status, dtype: int64

In [56]:
# from sklearn.preprocessing import LabelEncoder
# le=LabelEncoder()
# train_df['Home Status'] = le.fit_transform(train_df['Home Status'])

In [57]:
# train_df['Home Status'].value_counts()

0    41381
4    32672
3     7862
2        6
1        4
Name: Home Status, dtype: int64

## 1 Data Cleaning

In this section you can do all the Data cleaning part of all necessary imputations and treatments























## 2 Exploratory Data Analyis

In this section you can talk about the plots and the insights you have generated from the data

























## 3 Feature Engineering

In this section you can implement the feature engineering techniques for dimensionality reduction












## 4 Modelling + HyperParameter Tuning

In this you can build various ML models and try tuning the parameters involved to achieve better score

## Model 1

## Model 2 - Best Model

## Model 3